### PR TITLE
Correctly parse large ratingCount

### PR DESCRIPTION
**Pull request by necessary129**
Multiple commas and periods may be present in rating count of products.

### CODE REVIEW

**Comment by necessary129** [comment]
Wait. forgot to update the regex

**Comment by gsuberland** [comment]
Thanks for spotting this. I fixed this as part of some changes I made for v0.3 already, so this PR doesn't need to be applied.

**Comment by necessary129** [comment]
`string.replace` wouldn't replace all commas, right? only 1? shouldn't `replaceAll` be used? (as in this PR?)

**Comment by gsuberland** [comment]
Whoops, good catch. Fixed.

**Pull request closed without merging**
